all:
	gcc -O3 -std=gnu99 -m64 -Wall -Werror -I /home/ekaterina/Загрузки/FW_1.3.1_Lin64 -L /home/ekaterina/Загрузки/FW_1.3.1_Lin64/lib -o lab2 lab2.c -Llib/FW_1.3.1_Lin64/lib  -lfwBase -lfwSignal -lm
clean:
	rm -f lab2-*
